### ISSUE TITLE
Help command buttons being removed after pressing on a category

### ISSUE THREAD

**Issue by Doom306** [Ignite-Discord/Ignite#10]
**Describe the bug**
Help command doesnt show the buttons anymore after going to a category
**To Reproduce**
1. Type `ignt help`
2. Click on a category
3. Scroll down
4. See no button

**Comment by Overkill10117** [comment]
really? I see buttons

**Comment by Doom306** [comment]
Fixed- Forgot to update

**Comment by Doom306** [comment]
3.1.0
