### ISSUE TITLE
Enhancement Features

### ISSUE THREAD

**Issue by Doom306** [Ignite-Discord/Ignite#11]
To increase hangman, guess the number, drops, and trivia's reward by 10,000 credits. To make max of rob (work) 1,000,000 (from 2,000,000)

**Comment by Overkill10117** [comment]
wow

**Comment by Overkill10117** [comment]
can you make it like 1,000,000,000

**Comment by Doom306** [comment]
Too overkill so nope

**Comment by Overkill10117** [comment]
sad

**Comment by Doom306** [comment]
Ok

**Comment by Doom306** [comment]
Fixed this with the latest commit
